baseURL = 'https://foo-dogsquared.github.io/nixos-config'
defaultContentLanguage = 'en-US'
title = "foodogsquared's NixOS config"
timeZone = "UTC"

[params]
toc = true

[security.exec]
allow = [
  "^go$",
  "^asciidoctor$",
]
