borg:
    repos:
        services:
            password: ENC[AES256_GCM,data:oc+KxvGhTRPC7SbTSw0yTXOwyoemgPk0O9a3qK17,iv:vTeP9cRyrQaPSv1SvKhJSjBPrbDP3hd0FNtkfMNhTiY=,tag:RhG+d2iZZKyHs0g35UYd3g==,type:str]
grafana:
    oauth_client_secret: ENC[AES256_GCM,data:ZELA/Qar817K+jheyL4wIuE16B9jbvJpznAh+30q9j+BqTIRrmATstZMZxEfEpuPR/deN7z+QSzoNxLfN6wlOQ==,iv:G8Kp4/5k5c+jRuwhri69B9FiqX913rUBNIixvf6guXs=,tag:DYLGN5ebhpo3B4jjggiXOg==,type:str]
    database:
        password: ENC[AES256_GCM,data:FMuKd7qN3swSgth2bQD8pBB9xz92No/EzxeM,iv:rU1u9IrI3hdX305NlZryr/5dlsSgHEpNFwwEzpmCjII=,tag:IMJ6lSVQVYZUn3b8Ld8F6g==,type:str]
    users:
        admin:
            password: ENC[AES256_GCM,data:OaOZRG+RzyHS74mluFQdQ5sbAz1tLflBpR6NAQ==,iv:yPalKMaZBbmDn8IdazywdTtRuv0Ebn5UL+NaQb+vQx4=,tag:uNxU+mpgrXakZzCT0hNnGw==,type:str]
vouch-proxy:
    domains:
        foodogsquared.one:
            jwt-secret: ENC[AES256_GCM,data:wbl9lLyv2fY5tNNUm6k2RcsOb/2Qklrlq0QyThoiBBXKHQWOVOzGJnWgf/fa+EmpBnGOaN+SW0ZJragNYqFZpw==,iv:7fUWHUF9gnXdBUw32cfXCTMGqv3q2gwA+r/ybi3W5ro=,tag:nROn69VULdWDt6jIa5W2YQ==,type:str]
            client-secret: ENC[AES256_GCM,data:9MdP5wSTLI3MiwTkDOytj5jR1iM=,iv:pBwC+KElxqg+9rYfQ9gOHL/hs8dCoWmvnDonC6gOpxQ=,tag:krN4rGgkzfskdEn0v3Q2Zg==,type:str]
vaultwarden:
    env: ENC[AES256_GCM,data:gDM5bjo5/CBy4d+YoaAo//YD2bMrx+1h48l7hKc+SAT9okn9YGSQPqzSAWHLD7pLrn0yXBSaay4tVANnU6t82+aPPnrJKtONNMAR6z77CRm/3mUG2ih7HnEOLk7lf8uVO0OuNp0F6taefVjhYWwLE9nD7PoO0jxZBbIOsa2Slzn7YOIG8Pu34JsKL5dU4PFloyNuLyexhp69fDVKBj3v7z6w97vP6ThDFGyspiM53miHeAcKCKKVEM3x8yGgMfG+f/wFySSLhY2Xxheeiv+yS+qxraS3ymL04BY6ntPjFOokftN+w/R+L+4OXY9bUNMh1MsdI8A1Hwk/MqchZn4=,iv:mAst2dWbQKl3jCHlCHMYRCiX4UtH/svvNHlXC6j5zPc=,tag:9EE8bH85rojaCwgVlcK1tA==,type:str]
gitea:
    smtp_password: ENC[AES256_GCM,data:PjpY7EZd13LK+3LaUle0BwrgXlBV9rFKHY2KYwarfm0=,iv:xgYgYE0grZUdwuX0pgfqfwx13TgVNrJGYIujqnIqbsk=,tag:VTvTzPsz+pu0knYGzgmhRg==,type:str]
    db_password: ENC[AES256_GCM,data:4wpMoLEXGlWy4NV4+Kx1qnNnsLa+IT4coJylqSzq9/0=,iv:vF/p8tvr5AXBQslj8eTyTAuXfxIYzqO/PeeffTSSzl8=,tag:s7sHzhWG9LMpDB7Kvwp7gA==,type:str]
lego:
    env: ENC[AES256_GCM,data:z8aj+zXO2xZgrN/6Ctd8tw1bY9bDDWQdUTWyZD/DoNEnLIvQZ/ntmmdSp+iuFtm651XTtC+CleBFe1baEL1bwZFC4+6HNx8YEpllcbP3TVLS,iv:vsYunfAXjGe2oVUUJy2fDrrXDgjGAqzJGQMPygFVJgQ=,tag:aOWkcwbaEy/iOHAbfGG0kA==,type:str]
ssh-key: ENC[AES256_GCM,data:1YT7wI4ykEi1dis8+MlkLStri2vuHJs9tHefMNEdc1hA7/1KeS5KE7QHyn5xOSvBd9kO/mUjVptxfGiooqRy6dMN4U0JG+Akr+Ybsr5F1+ZltDPKwOYcnBpK47S5wm70OM4f9oiki8hJ4i0LrtuQq1L2x0pCCLuH2kNxbMgOomaRl8zW9vgR2B1lisRMv4pugCrNRkhqT9K2WTO3wOCZu9wj/C0IQwg07G0fW7Vuvt/p0/+rktRKDtm5F0aR4h8A+fbU6BxCfaQjHvu+A5aVCb2nvPTPtX80pOTerrcSTZe6bG5biN0n1Rq6xm9TtHLXvqFDTc1ES6dlAs0P4IgipGOeaCEvhkp+zCBF7iBg9Xj0kIJlXU1v36W8Xu7az+8fgYZXmizwgkw2eVJYpAnPx6oRmXQYpvHgzZJuVdvH/33E7Lg7j067bKC73fbQwtV97vBHfF+rrtr7w6IYwmxpRavyuB5Ze7xx48oVvMCInIk09KV2W3+ad+dZxrtOyVJHXzvh+H1UJeuAHIbsoH1b2C1sqOuhgu2BtmKIrfW8hX8Tjfc=,iv:XZtcySi+/XwPstuNyGa/nubABg+SE1r6iIfM/4n1+8Q=,tag:19W88F4xAxujD7VYtuVjBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yftkhugwrdnlpl45lthrhvvk720zza2nd085sxvjcxg2guavz3kquktplx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2xBRHdNTDRwdWQxS1VS
            WWlid21PQjhwSG9YN0ducEFSUFdENmFiNmhRCjduZm9wSHZmelNETlRncTB3RlNX
            YzNnSWhvVkRIUE1QNmFJQ3hKMUJVOFUKLS0tIE1lbVg0cUNsWVE2NTRxUnVLU3lF
            UDZXbzZzTUJKWHFBNGxjcy9UdGxMSzAKtMdXLsuvsmpjoDAK1GZSDHBWTLAl5iJY
            NRGL2GSkh72m1tQ5AXma34DR7WBNgwSkedLP6p/TR/J1ABpMJa551Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T06:09:53Z"
    mac: ENC[AES256_GCM,data:kuHyZrn1sGv3C+ShVCg+wDQZA9guD9kjd5LEBDUNDNT5hfm9JONxIQtY7GzOIRhBl7wLnms6eDnC1TSReV/JVzi+kOoU67xTz8AzCpPB0WxywUzHQS7xqstVjHzXPOYDBbwf4Y8j66zLxPX7XHvpQ+3RK91WelQmjmt2l4WrJ1o=,iv:DPOsv8A2uObRORa6PHEJ1q6eviHQDslMn0m0jQS0t30=,tag:dCGKfZSXsFEtgZYKeDNwDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
