name: "Update Firefox addons"
on:
  schedule:
    # Every week on Monday.
    - cron: '0 0 * * 1'
  push:
    branches:
      - master
    paths:
      - 'pkgs/firefox-addons'
jobs:
  update-firefox-addons:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set the date
        id: metadata
        run: echo "DATE=$(date +%F)" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v4
      - env:
          NIXPKGS_ALLOW_UNFREE: "1"
        run: nix develop --impure -c mozilla-addons-to-nix pkgs/firefox-addons/firefox-addons.json pkgs/firefox-addons/default.nix
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "firefox-addons: update as of ${{ steps.metadata.outputs.DATE }}"
          file_pattern: pkgs/firefox-addons/
